version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14

    working_directory: /go/src/github.com/cliffom/alfred
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: go get -v -t -d ./...
      - run:
          name: Run tests
          command: go test -v ./...